name-template: 'v$RESOLVED_VERSION'   # version-resolverì— ì •ì˜í•œ Labelsì— ë”°ë¼ ë²„ì „ì„ ì˜¬ë¦°ë‹¤.
tag-template: 'v$RESOLVED_VERSION'    # version-resolverì— ì •ì˜í•œ Labelsì— ë”°ë¼ ë²„ì „ì„ ì˜¬ë¦°ë‹¤.
categories:
  - title: 'ğŸ’¡ Features'
    labels:
      - 'ğŸŒˆ Feature'
  - title: 'ğŸ› Bug fixes'
    labels:
      - 'âš ï¸ Bug'
  - title: 'ğŸ¤¯ Inner Changes'
    labels:
      - 'ğŸ“¦ Chore'
      - 'ğŸ“ƒ Docs'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:   # major, minor, patchë¥¼ ì •ì˜í•˜ê³  ê·¸ ì™¸ì—ëŠ” patch ë²„ì „ì„ ì˜¬ë¦°ë‹¤.
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |   # ë¦´ë¦¬ì¦ˆ ë…¸íŠ¸ í˜•ì‹ì„ ì •ì˜í•œë‹¤.
  ## ğŸš€ ì´ë²ˆ ë²„ì „ì—ì„œëŠ” ì–´ë–¤ ê²Œ ë°”ë€Œì—ˆì„ê¹Œìš”?
  ---
  $CHANGES
no-changes-template: 'ì•—! ë³€ê²½ì‚¬í•­ì´ ì—†ì–´ìš”. ğŸ˜–'